AllCops:
  Exclude:
    - 'local/*'
  SuggestExtensions: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/ClassVars:
  Enabled: false
Metrics/ClassLength:
  Enabled: false