AllCops:
  SuggestExtensions: false
  TargetRubyVersion: "2.7.2"
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/ClassVars:
  Enabled: false
Metrics/ClassLength:
  Enabled: false