name: Lint and Test

on:
  push:
    paths:
    - '**'
  pull_request:
    paths:
    - '**'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      api-dir: ./api
    services:
      mysql:
        image: mysql/mysql-server:8.0.25
        env:
          MYSQL_ROOT_HOST: %
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mysql
        ports:
           - 3306:3306

    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Run bundle install
        working-directory: ./
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build and test with rspec
        working-directory: ./
        run: bundle exec rspec spec/config_spec.rb spec/mysql2_spec.rb
      # - name: Install Rubocop
      #   run: gem install rubocop
      # - name: Check code
      #   run: rubocop