name: Lint and Test

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      api-dir: ./api
      RAILS_VERSION: ${{ matrix.rails }}
    services:
      pg:
        image: postgres
        env:
          POSTGRES_USERNAME: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
        ports:
           - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7","3.0"]
        rails: ["5.0", "5.1", "5.2", "6.0", "6.1"]
        exclude:
          - ruby: "3.0"
            rails: "5.0"
          - ruby: "3.0"
            rails: "5.1"
          - ruby: "3.0"
            rails: "5.2"

    steps:
      - uses: actions/checkout@v1
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Run bundle install
        working-directory: ./
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Instrumentation Test
        working-directory: ./
        run: bundle exec rspec spec/postgres_spec.rb

      - name: Instrumentation Test ECS Metadata
        working-directory: ./
        run: bundle exec rspec spec/ecs_metadata_spec.rb

      - name: Instrumentation Test Rails
        working-directory: ./
        run: bundle exec rspec spec/rails_spec.rb

      - name: Integration Tests
        working-directory: ./
        run: bundle exec rspec spec/config_spec.rb