name: Lint and Test

on:
  push:
    paths:
    - '**'
  pull_request:
    paths:
    - '**'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      api-dir: ./api
    services:
      pg:
        image: postgres
        env:
          POSTGRES_USERNAME: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
        ports:
           - 5432:5432

    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Run bundle install
        working-directory: ./
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Instrumentation Test
        working-directory: ./
        run: bundle exec rspec spec/rails_spec.rb spec/ecs_metadata_spec.rb spec/postgres_spec.rb

      - name: Integration Tests
        working-directory: ./
        run: bundle exec rspec spec/config_spec.rb
      # - name: Install Rubocop
      #   run: gem install rubocop
      # - name: Check code
      #   run: rubocop